### PR TITLE
Builder pattern for elements.

### PR DESCRIPTION
**Pull request by nubis**
It's a basic builder pattern for Elements, makes it nicer to look at when you're building a large XML file in your rust code, no macros or quasiquoting involved, which could be a next iteration.

I guess this PR should merge smoothly, but I don't actually know how to use git and have been winging it for like 8 years now, so it's a coin toss...

### CODE REVIEW

**Comment by nxusr** [comment]
Merged as 3a4facb.

Your master branch has diverged from mine quite a bit (related of my habit of squash-merging), so I'd recommend `git reset`ing it to mine :)

What I normally do to minimise pain when contributing is to have my master track upstream master, and work on PRs in a separate branch (typically named for the feature I'm implementing). That way when upstream squash-merges into master, my branches (and other people's branches) can easily be rebased off it.

**Comment by nxusr** [comment]
@nubis I had a look at this after merging your PR, https://aturon.github.io/ownership/builders.html.

The added value of being able to reuse the builder has me convinced that the more flexible but verbose approach is worth it. I've moved your builder methods into `ElementBuilder` in 8319a95, and made them return a mutable reference so we can chain them across multiple lines if need be.

I've also bumped the version to 0.5.0, even though there's no backwards-incompatible API change just because the builder pattern is a pretty major addition.

**Comment by nubis** [comment]
That's cool, I think it's better. But one thing seems odd though, why use Into for attr instead of ToString?

With ToString you can write 
Element::new("node").attr("id", 11).text(22)

But with "into" it becomes:
Element::new("node").attr("id", 11.into()).text(22.into());

I initially had "Into", but then changed for "ToString", it kind of looks like the version you based ElementBuilder out of was my old implementation, instead of the one in this pull request. could that be the case?

cheers!
----nubis

**Comment by nubis** [comment]
Also, this PR includes changes to the README with proposed usage for the builder pattern, and importing the builder with a shorthand value to make composing less verbose (I would "use xmltree::ElementBuilder as E")

**Comment by nxusr** [comment]
Ahh, you're right! Sorry, I got lost in the 16 commits. Pushing an update.

**Comment by nubis** [comment]
Sorry about that. 

I did have some faith in this PR because overall github showed it understood only 3 files had changes as compared to the master branch in their repo, but I didn't take into account what your local copy looks like with all the other work you're doing.

This is actually the most friction I've ever caused with a contribution hehe :)

**Comment by nxusr** [comment]
Nah, don’t worry about it. I should’ve been more careful with the squash. I’d still recommend working on PRs in a branch just for convenience though :)

**Pull request closed without merging**
